-- Migration: Unify leads into a single table with source column
-- Run this in Supabase SQL Editor after deploying the new code.

-- 1. Create the unified leads table
create table if not exists horno.leads (
  id          bigint generated by default as identity primary key,
  source      text not null check (source in ('whatsapp', 'instagram')),
  contact     text not null,
  name        text,
  option      text not null,
  message     text,
  status      text not null default 'nuevo',
  metadata    jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

alter table horno.leads enable row level security;

create policy "anon can insert leads" on horno.leads
  for insert to anon with check (true);

create index if not exists leads_source_idx on horno.leads (source);
create index if not exists leads_created_at_idx on horno.leads (created_at desc);
create index if not exists leads_status_idx on horno.leads (status);

-- 2. Migrate existing whatsapp_leads data to the new table
insert into horno.leads (source, contact, name, option, message, status, created_at)
select
  'whatsapp',
  phone,
  name,
  option,
  message,
  status,
  created_at
from horno.whatsapp_leads
on conflict do nothing;

-- 3. Create a backward-compat view for external dashboards that read whatsapp_leads
create or replace view horno.whatsapp_leads_v as
select
  id,
  contact as phone,
  name,
  option,
  message,
  status,
  created_at
from horno.leads
where source = 'whatsapp';

-- 4. Verify migration (run this to check row counts)
-- select 'whatsapp_leads' as source, count(*) as total from horno.whatsapp_leads
-- union all
-- select 'leads (whatsapp)', count(*), from horno.leads where source = 'whatsapp'
-- union all
-- select 'leads (instagram)', count(*), from horno.leads where source = 'instagram';
