-- Migration: Create la_conve schema for La Conve event
-- Run this in Supabase SQL Editor.

create schema if not exists la_conve;

-- Team members for the event
create table if not exists la_conve.equipo (
  id          uuid primary key default gen_random_uuid(),
  slug        text unique not null,
  nombre      text not null,
  rol         text not null,
  bio         text,
  state       text not null default 'activo' check (state in ('activo', 'inactivo')),
  created_at  timestamptz not null default now()
);

alter table la_conve.equipo enable row level security;

create policy "anon can read equipo" on la_conve.equipo
  for select to anon using (true);

-- Unified leads table
create table if not exists la_conve.leads (
  id          bigint generated by default as identity primary key,
  source      text not null check (source in ('whatsapp', 'instagram')),
  contact     text not null,
  name        text,
  option      text not null,
  message     text,
  status      text not null default 'nuevo',
  metadata    jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

alter table la_conve.leads enable row level security;

create policy "anon can insert leads" on la_conve.leads
  for insert to anon with check (true);

create index if not exists la_conve_leads_source_idx on la_conve.leads (source);
create index if not exists la_conve_leads_created_at_idx on la_conve.leads (created_at desc);
create index if not exists la_conve_leads_status_idx on la_conve.leads (status);
